insert into Resource_Catalog
(product_name, product_type)
values
('Oxygen reserves','general'),
('Antipyretics (paracetamol)','general'),
('Anesthetic drugs/Muscular Relaxant','general'),
('Alcohol solutions (>70) and soap for handwashing','general'),
('Disposable masks (minimum P2)','general'),
('Disposable vinyl gloves','general'),
('Disposable hats','covid'),
('Disposable aprons','covid'),
('Visors','covid'),
('Disposable shoe covers', 'covid'),
('Covid test kits', 'covid');

insert into Action_Catalog
(action_name)
values
('NO ADDITIONAL ACTION NEEDED'),
('CALL BACK TOMORROW TO COMPLETE DATA'),
('FIND NEW PHONE NUMBER'),
('FIND AUTHORIZATION'),
('OTHER');


insert into Problem_Catalog
(problem)
values
('NO PROBLEM'),
('SOME DATA IS MISSING'),
('REFUSED TO SPEAK'),
('NO ANSWER'),
('WRONG PHONE NUMBER'),
('DOCTOR HAS QUIT');

insert into Questionnaire_Status_Catalog
(status)
values 
('QUESTIONNAIRE COMPLETED'),
('QUESTIONNAIRE COMPLETED PARTIALLY'),
('QUESTIONNAIRE NOT DONE'),
('THIS WAS A TEST'),
('OTHER - SEE COMMENTS');

-- Agregamos empleados de VoxMap falsos
insert into Personel_VM
(employee_name)
values 
('Armando'),
('Bruno'),
('Carla'),
('Daniela');


--PROVINCES
insert into Province
(province_name)
values
('Badakhsha'),
('Badghis'),
('Baghlan'),
('Balkh'),
('Bamyan'),
('Daykundi'),
('Farah'),
('Faryab'),
('Ghazni'),
('Ghor'),
('Hilmand'),
('Hirat'),
('Jawzjan'),
('Kabul'),
('Kandahar'),
('Kapisa'),
('Khost'),
('Kunar'),
('Kunduz'),
('Laghman'),
('Logar'),
('Maidan Wardak'),
('Nangarhar'),
('Nimroz'),
('Nuristan'),
('Paktika'),
('Paktya'),
('Panjsher'),
('Parwan'),
('Samangan'),
('Sar-e-Pul'),
('Takhar'),
('Uruzgan'),
('Zabul');

insert into district 
(district_name)
values
('Ab Band'),
('Ab Kamari'),
('Achin'),
('Adraskan'),
('Ahmadaba'),
('Ajristan'),
('Alasay'),
('Ali Abad'),
('Alingar'),
('Alishang'),
('Almar'),
('Anar Dara'),
('Anawa'),
('Andar'),
('Andarab'),
('Andkhoy'),
('Aqcha'),
('Arghandab'),
('Arghandab'),
('Arghanj Khwah'),
('Arghestan'),
('Argo'),
('Asad Abad'),
('Ashtarlay'),
('Atghar'),
('Aybak'),
('Azra'),
('Baghlan-e-Jadid'),
('Baghran'),
('Bagram'),
('Bagrami'),
('Baharak'),
('Baharak'),
('Bak'),
('Bakwa'),
('Bala Buluk'),
('Bala Murghab'),
('Balkh'),
('Balkhab'),
('Bamyan'),
('Bangi'),
('Bar Kunar'),
('Baraki Barak'),
('Barg-e-Matal'),
('Barmal'),
('Bati Kot'),
('Bazarak'),
('Behsud'),
('Bilcheragh'),
('Burka'),
('Chahab'),
('Chahar Asyab'),
('Chahar Darah'),
('Chak-e-Wardak'),
('Chakhansur'),
('Chal'),
('Chamkani'),
('Chapa Dara'),
('Chaparhar'),
('Char Bolak'),
('Char Burjak'),
('Charikar'),
('Charkent'),
('Charkh'),
('Charsadra'),
('Chawkay'),
('Chemtal'),
('Chisht-e-Sharif'),
('Chora'),
('Dahana-e-Ghori'),
('Daman'),
('Dand Wa Patan'),
('Dangam'),
('Dara'),
('Dara-e-Nur'),
('Dara-e-Pech'),
('Dara-e-Suf-e-Bala'),
('Dara-e-Suf-e-Payin'),
('Darayem'),
('Darqad'),
('Darzab'),
('Dasht-e-Archi'),
('Dasht-e-Qala'),
('Dawlat Abad'),
('Dawlat Abad'),
('Dawlatshah'),
('Dawlatyar'),
('Dawraz-e-Bala'),
('Dawraz-e-Payin'),
('Daychopan'),
('Daymirdad'),
('Deh-e-Shu'),
('Deh Bala'),
('Deh Sabz'),
('Deh Salah'),
('Deh Yak'),
('Dehdadi'),
('Dehrawud'),
('Dila'),
('DoLayna'),
('Doshi'),
('Duab'),
('Dur Baba'),
('Eshkashem'),
('Eshkmesh'),
('Estalef'),
('Farah'),
('Farkhar'),
('Farsi'),
('Farza'),
('Fayzabad'),
('Fayzabad'),
('Fereng Wa Gharu'),
('Feroz Koh'),
('Feroz Nakhchir'),
('Gardez'),
('Garmser'),
('Garzewan'),
('Gelan'),
('Ghazi Abad'),
('Ghazni'),
('Ghorak'),
('Ghorband'),
('Ghormach'),
('Ghoryan'),
('Giro'),
('Giyan'),
('Gizab'),
('Gomal'),
('Gosfandi'),
('Goshta'),
('Guldara'),
('Gulistan'),
('Gulran'),
('Gurbuz'),
('Guzara'),
('Guzargah-e-Nur'),
('Hazar Sumuch'),
('Hazrat-e-Sultan'),
('Hesa-e-Awal-e-Behsud'),
('Hesarak'),
('Hirat'),
('Hisa-e-Awal-e-Kohistan'),
('Hisa-e-Duwum-e-Kohistan'),
('Imam Sahib'),
('Injil'),
('Jabal Saraj'),
('Jaghatu'),
('Jaghatu'),
('Jaghuri'),
('Jaji'),
('Jaji Maydan'),
('Jalalabad'),
('Jalrez'),
('Jani Khel'),
('Jani Khel'),
('Jawand'),
('Jorm'),
('Kabul'),
('Kahmard'),
('Kajaki'),
('Kajran'),
('Kakar'),
('Kalafgan'),
('Kalakan'),
('Kaldar'),
('Kama'),
('Kamdesh'),
('Kandahar'),
('Kang'),
('Karukh'),
('Keshem'),
('Keshendeh'),
('Khadir'),
('Khak-e-Jabbar'),
('Khak-e-Safed'),
('Khakrez'),
('Khamyab'),
('Khan-e-Char Bagh'),
('Khan Abad'),
('Khanaqa'),
('Kharwar'),
('Khas Kunar'),
('Khas Uruzgan'),
('Khash'),
('Khashrod'),
('Khenj'),
('Khinjan'),
('Khogyani'),
('Khoshi'),
('Khost Wa Fereng'),
('Khulm'),
('Khuram Wa Sarbagh'),
('Khwahan'),
('Khwaja Bahawuddin'),
('Khwaja Dukoh'),
('Khwaja Ghar'),
('Khwaja Hejran'),
('Khwaja Sabz Posh'),
('Khwaja Umari'),
('Kiti'),
('Kofab'),
('Koh-e-Safi'),
('Koh Band'),
('Kohestanat'),
('Kohistan'),
('Kohistan'),
('Kohsan'),
('Koran Wa Monjan'),
('Kot'),
('Kunduz'),
('Kushk'),
('Kushk-e-Kuhna'),
('Kuz Kunar'),
('Lal Wa Sarjangal'),
('Lalpur'),
('Lash-e-Juwayn'),
('Lashkargah'),
('Lija Ahmad Khel'),
('Mahmood-e-Raqi'),
('Malistan'),
('Mandol'),
('Mandozayi'),
('Marawara'),
('Mardyan'),
('Markaz-e-Behsud'),
('Marmul'),
('Maruf'),
('Mata Khan'),
('Matun'),
('Maydan Shahr'),
('Maymana'),
('Maywand'),
('Mazar-e-Sharif'),
('Mehtarlam'),
('Mingajik'),
('Mir Bacha Kot'),
('Miramor'),
('Miyanshin'),
('Mizan'),
('Mohammad Agha'),
('Muhmand Dara'),
('Muqur'),
('Muqur'),
('Musa Khel'),
('Musa Qala'),
('Musahi'),
('Nad-e-Ali'),
('Nadir Shah Kot'),
('Nahr-e-Saraj'),
('Nahr-e-Shahi'),
('Nahrin'),
('Namak Ab'),
('Narang'),
('Nari'),
('Nawa'),
('Nawa-e-Barakzaiy'),
('Nawbahar'),
('Nawur'),
('Nawzad'),
('Nazyan'),
('Nerkh'),
('Nesh'),
('Nijrab'),
('Nika'),
('Nili'),
('Nurgal'),
('Nurgaram'),
('Obe'),
('Omna'),
('Pachir Wa Agam'),
('Paghman'),
('Panjab'),
('Panjwayi'),
('Parun'),
('Paryan'),
('Pasaband'),
('Pashtun Kot'),
('Pashtun Zarghun'),
('Pul-e-Alam'),
('Pul-e-Hisar'),
('Pul-e-Khumri'),
('Pur Chaman'),
('Pushtrod'),
('Qadis'),
('Qala-e-Kah'),
('Qala-e-Naw'),
('Qala-e-Zal'),
('Qalandar'),
('Qalat'),
('Qara Bagh'),
('Qara Bagh'),
('Qaram Qul'),
('Qarghayi'),
('Qarqin'),
('Qaysar'),
('Qurghan'),
('Qush Tepa'),
('Raghestan'),
('Rashidan'),
('Reg'),
('Reg-i-Khan Nishin'),
('Rodat'),
('Rostaq'),
('Rukha'),
('Ruy-e-Duab'),
('Sabari'),
('Saghar'),
('Salang'),
('Sancharak'),
('Sang-e-Takht'),
('Sangin'),
('Sar-e-Pul'),
('Sar Kani'),
('Sar Rawzah'),
('Sayad'),
('Saydabad'),
('Sayed Karam'),
('Sayed Khel'),
('Sayghan'),
('Shah Joi'),
('Shah Wali Kot'),
('Shahid-e-Hassas'),
('Shahr-e-Buzorg'),
('Shahrak'),
('Shahrestan'),
('Shakar Dara'),
('Shaki'),
('Shamal'),
('Shamul Zayi'),
('Sharak-e-Hayratan'),
('Sharan'),
('Shawak'),
('Shekh Ali'),
('Sherzad'),
('Shibar'),
('Shiberghan'),
('Shibkoh'),
('Shigal'),
('Shighnan'),
('Shindand'),
('Shinkay'),
('Shinwar'),
('Shinwari'),
('Shirin Tagab'),
('Sholgareh'),
('Shorabak'),
('Shortepa'),
('Shuhada'),
('Shutul'),
('Sozmaqala'),
('Spera'),
('Spin Boldak'),
('Surkh-e-Parsa'),
('Surkh Rod'),
('Surobi'),
('Surobi'),
('Tagab'),
('Tagab'),
('Tala Wa Barfak'),
('Taloqan'),
('Tani'),
('Tarnak Wa Jaldak'),
('Taywarah'),
('Terezayi'),
('Teshkan'),
('Tirinkot'),
('Tolak'),
('Turwo'),
('Urgun'),
('Waghaz'),
('Wakhan'),
('Wal-e-Muhammad-e-Shahid'),
('Wama'),
('Waras'),
('Warduj'),
('Warsaj'),
('Washer'),
('Watapur'),
('Waygal'),
('Wazakhah'),
('Wormamay'),
('Yaftal-e-Sufla'),
('Yahya Khel'),
('Yakawlang'),
('Yamgan'),
('Yangi Qala'),
('Yawan'),
('Yosuf Khel'),
('Zadran'),
('Zanakhan'),
('Zaranj'),
('Zarghun Shahr'),
('Zari'),
('Zebak'),
('Zheray'),
('Zindajan'),
('Ziruk'),
('Zurmat');

--- Agregamos un par de hospitales falsos
insert into hospital
(hospital_name, address, latitude, longitude, district, province, hospital_type, MOPH_number)
values
('Angeles','Periferico Sur',100,200, 4,5,'Distrital','A10-23'),
('SEDNA','EDOMEX',200,1, 2,3,'Regional','10-38'),
('Cardiologia','Centro',3,4, 4,11,'Provincial','93-837')


insert into update_hospital 
(name_responder, id_personel_vm,id_hospital,id_questionnare_status,id_problem_status,id_action_status,funds,additional_comments,update_date)
values
('Abdul -Ghani', 1,1,1,1,1,  'No','','2021-06-22 19:10:25-07'),
('Abdul -Shakor', 1,2,3,1,1,  'Yes-Private','','2021-06-23 19:10:25-07');
